### PR TITLE
Adds media style for select input width to fix cross list bleed on mobile

### PR DESCRIPTION
**Pull request by bdc34**
For mobile screen sizes on the submission add cross step, this stops the select box from bleeding off the right of the screen.

This is more of a stop gap measure. A select is not really appropriate for the cross list on mobile. A better solution to this should be found.

See https://arxiv-org.atlassian.net/browse/ARXIVNG-2200 for screenshots.

ARXIVNG-2200

### CODE REVIEW

**Review by mhl10 — APPROVED** [review]
Screenshot looks good to me. I think this solution will be fine as a stop-gap. I'd consider adding a brief explanation to `DECISIONS.md` so that this information isn't lost; perhaps future UI/UX specialist can revisit.

**Comment by erickpeirson** [comment]
> A select is not really appropriate for the cross list on mobile. A better solution to this should be found.

Curious to hear more about what you mean. Are you referring to the length of the options list? If there is a more appropriate solution we should consider it.

**Comment by bdc34** [comment]
@erickpeirson Yes, the list is long and when the list is accessed, each item in the list will still bleed off the screen. Adding multiple crosses would be cumbersome.

I don't have any suggestions. I'm sure the new UX person will have suggestions about improving the submit on mobile.

**Review by erickpeirson — APPROVED** [review]
This looks good. The travis failures appear to be unrelated, so can disregard

**Pull request merged**
