### PR TITLE
Styling fixes and tweaks

### LINKED ISSUE #149: Options in secondary classification list bleed off screen on mobile
@erickpeirson Yes, the list is long and when the list is accessed, each item in the list will still bleed off the screen. Adding multiple crosses would be cumbersome.

I don't have any suggestions. I'm sure the new UX person will have suggestions about improving the submit on mobile.

_Originally posted by @bdc34 in https://github.com/arXiv/arxiv-submission-ui/pull/148#issuecomment-518818414_

### PR DESCRIPTION
**Pull request by erickpeirson**
This implements a quite a few little tweaks and fixes to styling in the UI, mostly focused on mobile-friendliness. This includes:

- More compact display of titles on each page
- Fixes for collapsing issues on small displays, e.g. buttons on the manage submissions page
- Fixes for elements that overflow the viewport on small displays, e.g. form inputs with add-ons
- Some changes to breakpoints on tablet display to make more efficient use of screen real-estate

Bumps filemanager build to https://github.com/arXiv/arxiv-filemanager/pull/50 in the docker-compose, incorporating the latest changes to errors and warnings handling.

Also fixes a bug on the PDF preview involving a missing ETag header.

A few examples (not everything):

Fixes #149

### CODE REVIEW

**Comment by erickpeirson** [comment]
Note that this doesn't fix everything for file upload on mobile -- should come back to that

**Review by DavidLFielding — APPROVED** [review]
I'm very happy to see the ETag in there. I'm less familiar with the css side of things and the exact rationale for some of the tweaks so I really can't evaluate the styling tweaks at this point. 

The screenshots of small displays look fine to me but having the before/after comparison might be useful in a situation like this. Seeing them makes me want to upgrade to a phone with a huge screen.

**Comment by erickpeirson** [comment]
Sounds good. Will give @mhl10 a chance to look before merging. I expect we will continue to revise the styling, just wanted to fix some obvious things

**Review by mhl10 — APPROVED** [review]
Looks good to me!

**Pull request merged**
