### PR TITLE
accessibility edits

### PR DESCRIPTION
**Pull request by SBBCornell**
Includes many icon changes, also added aria labels and fixed duplicate IDs, and some style edits. Dependent on arxiv-base branch "ARXIVNG-2865" for compliance (PR #164 in base repo).

### CODE REVIEW

**Comment by SBBCornell** [comment]
I added a new commit with the changes from David's "The Revival" pr (without which this branch cant be spun up) and just wanted to clarify that its duplicating the work from David's branch.

**Comment by SBBCornell** [comment]
> I added a new commit with the changes from David's "The Revival" pr (without which this branch cant be spun up) and just wanted to clarify that its duplicating the work from David's branch.

I reset and the "revival" commit is removed from this pr, sorry for the confusion :-)

**Comment by DavidLFielding** [comment]
I pulled the branch and rebuilt submission UI. I'm seeing following error when I bring it up:

arxiv-submission-ui       |   File "/opt/arxiv/submit/controllers/ui/__init__.py", line 16, in <module>
arxiv-submission-ui       |     from ..util import load_submission
arxiv-submission-ui       | ModuleNotFoundError: No module named 'submit.controllers.util'

I believe this is one of the fixes I made in the 'revival' branch that has been merged into develop. 
I may go back and try develop branch just to be sure I didn't miss something.

**Comment by SBBCornell** [comment]
rebased with latest develop branch (includes David's revival changes)

**Review by mhl10 — APPROVED** [review]
These changes look fine to me!

**Pull request merged**
