### PR TITLE
ARXIVNG-2786 Submission UI "The Revival" PR

### PR DESCRIPTION
**Pull request by DavidLFielding**
The recent commit on October 24th indicated "minor fix in travis config" when in fact an apparently incomplete refactor was included in the commit. Controllers were moved into a subdirectory 'ui' while some paths importing these modules were not updated correctly.

I'm able to do a complete rebuild and bring up the "Manage My Submissions" page. I'm able to run through the entire submission process all the way through to the submit process.

I'd like a few team members to try bringing up this branch. Please report any issues you may have.

Since some of you experienced problems with the older branch that I was able to get running on my laptop I suspect there may still be local issues. I will work to resolve any additional issue that might be laptop specific.

I'm definitely interested in Shamsi and Brian trying to run this branch since they both experienced problems running Submission UI on their laptops.

### CODE REVIEW

**Review by mhl10 — COMMENTED** [review]
These changes look fine but I'll hold off on submitting my approval until I've had a chance to try it.

**Comment by mhl10** [comment]
Travis is showing one `ImportError` and one `ModuleNotFoundError` when running the tests.

**Comment by bdc34** [comment]
I can run this and it gets to the point of the sub-ui waiting on the compiler service. 

The compiler service is not starting because its image is hosted on AWS ECR and the quick-start instructions do no include any instructions on how to get that image.

**Comment by mhl10** [comment]
I ran `docker-compose rm -v` followed by `docker-compose pull`. I'm getting 'manifest' errors for `submission-ui` and for `mock-classifier`. The latter error seems expected, but should I still be getting the error for `submission-ui`?

**Comment by SBBCornell** [comment]
I was able to successfully pull up the UI. I still get the usual errors when running docker-compose pull (mock vault and submission ui). I ignored them and was able to spin it up. 

I ran through submission twice. The first time each step was extremely slow and the process "com.docker.hyperkit" used a lot of CPU (800+). The second time each step was very fast and that same process never went above 100. 

I get this message when uploading my sample TeX file:
" File 'sample.tex' does not end with newline (\n), TRUNCATED?"
I am able to use this same sample file on classic submit without issue. I ignored the message and was able to upload it.

There was some strange behavior when I first uploaded a PDF file that is used as a figure in the TeX. After about 5 minutes it was still processing the upload. I refreshed the page and it then showed that the file had uploaded. The second time I tried the same step I did not have this issue, everything uploaded very quickly. 

Overall worked great!

**Review by SBBCornell — APPROVED** [review]
This branch working on my end, Im able to spin it up and successfully submit articles.

**Comment by SBBCornell** [comment]
Update: I tried to test a third submission after 10 minutes and got a 500 error "Service Unavailable".  I spun it up again and its working. Just wanted to mention for the record.

**Pull request merged**
