### PR TITLE
ARXIVNG-1788 ARXIVNG-1773  ARXIVNG-1789 ARXIVNG-1776 ARXIVNG-1791 ARXIVNG-1794 ARXIVNG-1790 and lots o' little fixes

### PR DESCRIPTION
**Pull request by erickpeirson**
This fixes a few issues that cropped up during the last review.

- [ARXIVNG-1773 Metadata page produces 500 error](https://arxiv-org.atlassian.net/browse/ARXIVNG-1773)
- [ARXIVNG-1789 "View raw log" appears immediately after pressing process files button](https://arxiv-org.atlassian.net/browse/ARXIVNG-1789)
- [ARXIVNG-1788 Uploading PDF file via submission UI results in 500 error. Submission UI becomes non functional.](https://arxiv-org.atlassian.net/browse/ARXIVNG-1788)
- [ARXIVNG-1791 Submission UI: Process Pages: autotex log only displayed in TeXLive Compiler Summary when compilation is successful](https://arxiv-org.atlassian.net/browse/ARXIVNG-1791)
- [ARXIVNG-1481 Communicate DB failure and other process interrupts to the UI](https://arxiv-org.atlassian.net/browse/ARXIVNG-1776)
- [ARXIVNG-1794 Use a small cookie to keep track of which steps the user has completed (esp for optional steps with no data)](https://arxiv-org.atlassian.net/browse/ARXIVNG-1794)
- [ARXIVNG-1790 Submission UI: Process Pages: Previous list of compilations does not always display state](https://arxiv-org.atlassian.net/browse/ARXIVNG-1790)

It also does a lot of DRYing-out of the ``routes.ui`` module. 

And I made other little tweaks and fixes that came up along the way.

I would not recommend doing a line-by-line review of code, as the diff is pretty huge. Instead, I'd suggest using the same approach as for https://github.com/arXiv/arxiv-submission-ui/pull/59

You may need to clear out any previous containers/volumes, and will definitely need to rebuild the submission-ui container.

```bash
cd /path/to/arxiv-submission-ui
docker-compose rm -v     # Press `y` when prompted.
mkdir /tmp/foo     # Compiler service will use this.
HOST_SOURCE_ROOT=/tmp/foo COMPILER_DOCKER_IMAGE=[ will share via slack ]:0.8 docker-compose build
HOST_SOURCE_ROOT=/tmp/foo COMPILER_DOCKER_IMAGE=[ will share via slack ]:0.8 docker-compose up
```

### CODE REVIEW

**Comment by erickpeirson** [comment]
Thanks! Let's keep this PR open and I'll look at those issues. I have a
couple of other fixes to push, and will then ask for rereview

**Comment by eawoods** [comment]
Sooooo close!
New details to solve:
- 403 error on delete from either the start page or within submission process (at least it's not 500 anymore)
- Logs show a complete compiler run with TeX log in Terminal, but interface continues to show "Processing"

**Comment by erickpeirson** [comment]
@eawoods Ok, ready for another look!

**Comment by DavidLFielding** [comment]
Looks much better. No obvious failures (especially when I'm using a new token). 

There may be issues with file manager v0.0 that have been addressed in more recent PRs.

**Comment by DavidLFielding** [comment]
General comment on large PRs. The description indicates not to attempt a detailed code review. Tickets covered are of various flavors where some may result in prescribed change while others may result in alternate work. 

I find it difficult to "calculate" my test suite traversal without more detail on the bugs fixes. Some are clearly obvious. Other leave wiggle room for what is to be done. And some I'm simply curious about at the overview level. 

Example, I'm interested in what the problem/fix is for the DB failure (ARXIVNG-1776). The ticket describes the problem. There is nothing on the solution. I think a simple "identified bug and fixed" is sufficient to some extent. More details might help in the event someone else runs into a similar problem. I'm curious if this DB issue is a problem that might be duplicated elsewhere.

In other tickets, I often describe a problem and present multiple solutions or go beyond a single solution. A simple note would tell me what was done and whether other suggestions were implemented or dropped. In these cases, I'm not sure how to interpret completeness when a ticket is deemed fixed.

This is minor stuff and only intended to improve communications about what is happening. This PR is great, fixes a lot of small nagging issues, but I would like to put forward my best effort when trying to perform testing so the more details the better (IMHO).

**Pull request merged**
