### PR TITLE
Arxivng 2945 more edits

### PR DESCRIPTION
**Pull request by SBBCornell**
This branch adds more style edits to submission related to ticket 2945:
https://arxiv-org.atlassian.net/browse/ARXIVNG-2945

Representative screenshots are attached. The changes include:
- introduction of a serif font, 'Computer Modern' (which was invented and still used by TeX). The serif font is applied to regular paragraphs of text only (not for alert messages, action areas, informational boxes, etc). If this change is approved for submission-ui I think we should probably host the font in base instead, but its included in this branch for simplified testing. 
- Improved margins and spacing, especially on the preview page.
- Some further refinements to the display of the process page.
- Various text clarifications and edits.
- Subtle accessibility-related color changes to the steps pagination.

license-page
preview-page
process-page

### CODE REVIEW

**Comment by SBBCornell** [comment]
Ive updated this PR to remove the serif font. I think the spacing changes in this PR are helpful, plus there is new verbiage from admins and some small a11y color fixes which would be good to get merged in. I'll tackle font change suggestions in a completely separate and clean ticket/PR. 

New screenshots are below for review. 

Screen Shot 2020-02-13 at 9 41 01 AM
Screen Shot 2020-02-13 at 9 43 36 AM
Screen Shot 2020-02-13 at 9 45 48 AM

**Review by mhl10 — APPROVED** [review]
These changes look great, even though we are deciding to defer on the font change for now.

**Review by bdc34 — APPROVED** [review]
Looks good.

I don't see the discussion about the font but I think using Computer Modern was considered before. 

I don't know where the conversations about that are but I think they way it went was that there was a feeling that the serif font strongly indicated that the text was from the content of a paper.

**Review by DavidLFielding — APPROVED** [review]
Looks good!

**Pull request merged**
