### PR TITLE
ARXIVNG-1425 Correct upload warnings and errors

### PR DESCRIPTION
**Pull request by erickpeirson**
Upload new file with errors:

image

Upload file with warnings:

image

Workspace is in ERRORS state:
image

Workspace is in READY_WITH_WARNINGS state:
image

### CODE REVIEW

**Comment by erickpeirson** [comment]
Depends on https://github.com/arXiv/arxiv-filemanager/pull/30

**Comment by erickpeirson** [comment]
This still needs some work -- looks like some error details aren't coming back from the file management service, so once those are there we can confirm that everything makes sense.

**Comment by DavidLFielding** [comment]
I will need to try running this to experiment with the process control logic. In my opinion the top level error messages are confusing in a sense because we start with "Upload successful" in the case where there are warnings and errors. I think we might discuss being more clear in this top level statement.

I will need to investigate the problem you mention with details not coming back from file manager service.

I will also note that the first screenshot demonstrates the potential 'missing refs' error. In the above example the .bib has already been removed such that subsequent actions eliminate the error. This has been fixed in the upcoming PR I am working on. (Actually it was fixed before that but I have since discovered a bug that is fixed in upcoming PR.)

I am currently working to fix the 'missing refs' in legacy system. This work might inspire additional changes in this area in NG.

**Comment by erickpeirson** [comment]
Would "upload completed, with (errors|warnings)" make more sense?

**Comment by erickpeirson** [comment]
Ok, changed the wording

**Pull request merged**
