### PR TITLE
ARXIVNG-1375 set up mailhog for testing, fixes for http status codes

### PR DESCRIPTION
**Pull request by erickpeirson**
As usual, I snuck in just enough minor unrelated fixes to really spam this PR....mostly these changes are bringing this project up to speed with https://github.com/arXiv/arxiv-base/pull/107.

The main reason this PR is here is to introduce mailhog in the docker-compose, so that you can actually see what's happening with confirmation e-mails. To try this out (in conjunction with https://github.com/arXiv/arxiv-submission-core/pull/58), do this:

```bash 
docker-compose rm -v 
docker-compose pull
mkdir /tmp/foo     # Compiler service will use this.
HOST_SOURCE_ROOT=/tmp/foo COMPILER_DOCKER_IMAGE=[ will share via slack ]:0.8 docker-compose build
HOST_SOURCE_ROOT=/tmp/foo COMPILER_DOCKER_IMAGE=[ will share via slack ]:0.8 docker-compose up
```

Once everything spins up, head over to http://127.0.0.1:8025/. 

Proceed through the submission process. When you finalize the submission (past the point of no return!) you should get an e-mail in mailhog.

image

### CODE REVIEW

**Comment by erickpeirson** [comment]
> Progress bar has regressed in a new way; when beginning a new submission all of the steps through preview are highlighted in advance.

I believe that this is just an artifact of testing. The cookie is based on the submission ID, which gets re-used every time you blow away your testing stack and start again. Can you try clearing that cookie and seeing if it resolves?

**Comment by erickpeirson** [comment]
> Attaching the abs preview to the HTML email is a fantastic idea. Mid-document style sheet embeds are supported in spotty ways - we may want to take a look at the unstyled version or remove the styling completely to be more predictable across email clients.

Let's talk more about this; my experience with styling HTML e-mails is limited. In any case we would implement this in https://github.com/arXiv/arxiv-submission-core/pull/58 rather than the UI

**Comment by eawoods** [comment]
Cookie showing extra progress: oh yeah, should have realized that :P 
Recording for future selves: email discussion has resolved, in-body CSS will be removed and a bit added to head, role="presentation" added to display table.

**Comment by erickpeirson** [comment]
Per discussion, will link to abs preview in HTML part as part of [ARXIVNG-2006](https://arxiv-org.atlassian.net/browse/ARXIVNG-2006).

**Pull request merged**
