### PR TITLE
Fix progress bar bugs introduced by workflow refactor

### PR DESCRIPTION
**Pull request by bdc34**
This uses the workflow to check if the stages are before the current stage or after it.

This merges to ARXIVNG-2886 due to branching from there.

### CODE REVIEW

**Review by SBBCornell — COMMENTED** [review]
Im hitting a 500 error when I get to the optional metadata page. It's working great up to that point.

**Comment by SBBCornell** [comment]
Also it looks like the confirmation step is gone from the nav/steps... which I think is great! Reducing steps is fantastic but wanted to double check.

**Comment by SBBCornell** [comment]
> Im hitting a 500 error when I get to the optional metadata page. It's working great up to that point.

I am also hitting this error when running develop, so it doesnt appear to be related to this PR.

**Comment by bdc34** [comment]
> Also it looks like the confirmation step is gone from the nav/steps... which I think is great! Reducing steps is fantastic but wanted to double check.

That was not intentional...but great!

**Comment by bdc34** [comment]
> > Im hitting a 500 error when I get to the optional metadata page. It's working great up to that point.
> 
> I am also hitting this error when running develop, so it doesnt appear to be related to this PR.

I'll take a look at that.

**Comment by SBBCornell** [comment]
> > Also it looks like the confirmation step is gone from the nav/steps... which I think is great! Reducing steps is fantastic but wanted to double check.
> 
> That was not intentional...but great!

We still need users to hit that final screen because there is important messaging, but I completely agree it doesn't need to be part of the pagination.

**Comment by bdc34** [comment]
> > Im hitting a 500 error when I get to the optional metadata page. It's working great up to that point.
> 
> I am also hitting this error when running develop, so it doesnt appear to be related to this PR.

I've fixed this 500 error on optional metadata.

It also looks like I chopped off the confirmation step.

**Comment by mhl10** [comment]
@bdc34 did you intend to set the base branch for this PR to ARXIVNG-2886?

**Comment by bdc34** [comment]
> @bdc34 did you intend to set the base branch for this PR to ARXIVNG-2886?

I had it set to ARXIVNG-2886 but then that got merged to develop so I change the base of this PR.

**Comment by mhl10** [comment]
> > @bdc34 did you intend to set the base branch for this PR to ARXIVNG-2886?
> 
> I had it set to ARXIVNG-2886 but then that got merged to develop so I change the base of this PR.

OK. Changeset looked bigger than I expected.

**Comment by bdc34** [comment]
> > > @bdc34 did you intend to set the base branch for this PR to ARXIVNG-2886?
> > 
> > 
> > I had it set to ARXIVNG-2886 but then that got merged to develop so I change the base of this PR.
> 
> OK. Changeset looked bigger than I expected.

I know what you mean. When I did something like this earlier the change set went back to just what were new commits. I'll need to be careful with this merge.

**Comment by bdc34** [comment]
> > > Also it looks like the confirmation step is gone from the nav/steps... which I think is great! Reducing steps is fantastic but wanted to double check.
> > 
> > 
> > That was not intentional...but great!
> 
> We still need users to hit that final screen because there is important messaging, but I completely agree it doesn't need to be part of the pagination.

I added back the confirmation step but it is excluded from the pagination.

**Comment by SBBCornell** [comment]
I just tested and it looks great!

**Review by SBBCornell — APPROVED** [review]

**Pull request merged**
