### PR TITLE
Fixing ordering of files on upload step.

### LINKED ISSUE #83: Use string.casefold() before sorting files
Screenshot 2019-06-04 16 17 10

> Nit: python's lexicographic sorting feels unnatural for a list of files/folders since it's not how most operating systems (AFAIK) sort files/folder names. I would be inclined to apply `string.casefold()` before sorting.

_Originally posted by @mhl10 in https://github.com/arXiv/arxiv-submission-ui/pull/80_

### PR DESCRIPTION
**Pull request by bdc34**
Fixes ordering of files and puts root files at top of list.

Moved group_files to upload controller.

Fixes #83

### CODE REVIEW

**Review by jimentwood — APPROVED** [review]
I'm not reviewing the code in detail, but don't see any red flags.

**Comment by jimentwood** [comment]
I see the output on issue #83 looks good.

**Comment by mhl10** [comment]
Looks good from screenshot in #83. I'll give it a quick try in my environment.

**Comment by bdc34** [comment]
> Looks good from screenshot in #83. I'll give it a quick try in my environment.

That would be good. I cannot actually upload files and I faked this file list.

**Comment by mhl10** [comment]
The screenshot below shows all the files starting with capital letters listed first. #83 was originally advocating for sorting with case folding, like this:

```
alpha.pdf
Alpha.pdf
beta.png
Gamma.txt
delta
epsilon.gif
some_folder/
     aardvark.png
     cute_kitten.png
     Cuter_Kitten.png
     sad_rhino.jpg
zeta
Zeta_cool
```

I still think sorting with case folding would be better/more natural than python's default sorting for a file tree. I also think folders ought to be sorted the same way, among the files (not all at the bottom), though this is at odds with @jimentwood 's suggestion in the issue. 

Screenshot 2019-06-14 09 47 58

**Comment by mhl10** [comment]
Per discussion with @jimentwood I think it's OK to group the folders at the bottom (or top).

**Comment by bdc34** [comment]
> The screenshot below shows all the files starting with capital letters listed first. #83 was originally advocating for sorting with case folding, like this:

Casefold has been added.

**Review by mhl10 — APPROVED** [review]
Thanks for the changes. Looks good!

**Pull request merged**
