### PR TITLE
Adds instructions on how to get ECR images

### PR DESCRIPTION
**Pull request by bdc34**
The docs lacked working instructions for getting the quick start running. There was no description on how to access ECR.

ARXIVNG-2790

### CODE REVIEW

**Comment by SBBCornell** [comment]
I tested running through your instructions, since I had not set up ECR credentials before. Useful! Some questions came up that might not be errors:

On line 28: I dont see a link to download csv file. I am able to view and copy my Key ID and Secret from the final window though. 

line 30: perhaps include this link with install instructions? 
https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-install.html

line 30: is the region to use "us-east-1"? And do we need to input anything for "Default output format"?

line 35: I got this error when running "aws ecr list-image ...."
An error occurred (RepositoryNotFoundException) when calling the ListImages operation: The repository with name 'arxiv' does not exist in the registry with id '626657773168'

line 101: maybe add 'docker system prune" also? The rm command on its own doesnt seem to get rid of any containers for me, but if I follow up with prune then they are gone.

**Comment by bdc34** [comment]
> On line 28: I dont see a link to download csv file. I am able to view and copy my Key ID and Secret from the final window though.
Hum... not sure what to say. I get a download link. I'll just leave it as is.
 
> line 30: perhaps include this link with install instructions?
> https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-install.html

Done.
> line 30: is the region to use "us-east-1"? And do we need to input anything for "Default output format"?

Added.

> line 35: I got this error when running "aws ecr list-image ...."

Oh, that was a mistake on my part. Fixed.

> line 101: maybe add 'docker system prune" also? The rm command on its own doesnt seem to get rid of any containers for me, but if I follow up with prune then they are gone.

I'm just doing the ECR stuff so I'm not going to change the rest of the docs.

**Review by SBBCornell — APPROVED** [review]
its working successfully for me!

**Comment by DavidLFielding** [comment]
You've already fixed the list-images (repository specific) command.

The command to list all of the repositories in the arXiv ECR might be more useful as a starting point:

'aws ecr describe-repositories'

**Review by DavidLFielding — APPROVED** [review]
Looks good. Works for me!

**Pull request merged**
